spring:
  security:
    oauth2:
      client:
        registration:  # OAuth2 클라이언트 등록 정보
          google:
            client-id: 667368354987-v8mk4av6ndmqqj6f3uembit4e94ke6b4.apps.googleusercontent.com  # Google OAuth 클라이언트 ID
            client-secret: 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  # Google OAuth 클라이언트 Secret
            scope:  # OAuth2 요청 시 동의 항목
              - email  # 사용자 이메일 정보
          kakao:
            client-id: 578551f7749021ab54e580e239323129  # Kakao OAuth 클라이언트 ID
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"  # 인증 성공 후 리다이렉트될 URL
            client-authentication-method: client_secret_post  # 클라이언트 인증 방식 (POST로 Secret 전달)
            authorization-grant-type: authorization_code  # 인증 방식 (Authorization Code Grant)
            scope: account_email  # 동의 항목 (프로필 닉네임, 계정 이메일)
            client-name: Kakao  # 클라이언트 이름 (Spring Security에서 구분용)
          naver:
            # Naver OAuth는 Spring Security에서 기본 제공하지 않기 때문에 설정을 수동으로 입력해야 함
            client-id: BN4UeqbsmQd2SvCZtjBn  # Naver OAuth 클라이언트 ID
            client-secret: m4N6xfgKtk  # Naver OAuth 클라이언트 Secret
            scope:  # OAuth2 요청 시 동의 항목
              - email  # 사용자 이메일 정보
            client-name: Naver  # 클라이언트 이름 (Spring Security에서 구분용)
            authorization-grant-type: authorization_code  # 인증 방식 (Authorization Code Grant)
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"  # 인증 성공 후 리다이렉트될 URL
        provider:  # OAuth2 인증 제공자 (Provider) 별 설정
              kakao:
                authorization-uri: 'https://kauth.kakao.com/oauth/authorize'  # Kakao OAuth2 인증 요청 URI
                token-uri: 'https://kauth.kakao.com/oauth/token'  # Kakao OAuth2 토큰 발급 URI
                user-info-uri: 'https://kapi.kakao.com/v2/user/me'  # Kakao 사용자 정보 요청 URI
                user-name-attribute: id  # 사용자 고유 식별자 속성 (Kakao에서 `id`가 사용됨)
              naver:
                authorization-uri: 'https://nid.naver.com/oauth2.0/authorize'  # Naver OAuth2 인증 요청 URI
                token-uri: 'https://nid.naver.com/oauth2.0/token'  # Naver OAuth2 토큰 발급 URI
                user-info-uri: 'https://openapi.naver.com/v1/nid/me'  # Naver 사용자 정보 요청 URI
                user-name-attribute: response  # 사용자 정보의 루트 속성 키 (Naver는 JSON 응답의 `response` 키를 사용)